name: Other Issue
description: Report an issue that doesn't fit into other categories
title: "[Other]: "
labels: ["other"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue
      placeholder: Describe your issue here...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here
    validations:
      required: false
